# ReleaseHx configuration for DocOps/issuer repository
# Configuration for testing real GitHub data with dynamic labels enabled

# API configuration for GitHub
api:
  from: github
  project: DocOps/issuer
  href: https://api.github.com/repos/DocOps/issuer/issues
  auth:
    key_env: RELEASEHX_API_KEY

# Sources configuration
sources:
  note: issue_body
  note_pattern: /^## Release Note.*\n\n(?<note>.+)/ms
  summ: issue_heading
  head: issue_heading

rhyml:
  pasterize_summ: true

tags:
  deprecation:
    text: Deprecation
  release_note_needed:
    slug: needs:note
  internal:
    text: Internal

parts:
  label_prefix: "part:"
  cli:
    text: CLI
    head: CLI
    icon: terminal
  imyml:
    text: IMYML
    head: IMYML
    icon: hacker-news
  documentation:
    text: documentation
    head: Documentation
    icon: book
  api_clients:
    text: API Clients
    head: API Clients
    icon: plug

types:
  removal:
    slug: "type:removal"
    text: removal
    head: Removed
    icon: exclamation-triangle
  feature:
    slug: "type:feature"
    text: new feature
    head: Added
    icon: plus-square-o
  bugfix:
    slug: "type:bug"
    text: bug fix
    head: Fixed
    icon: bug
  improvement:
    slug: "type:improvement"
    text: improvement
    head: Improved
    icon: wrench
  deprecation:
    slug: "type:deprecation"
    text: deprecation
    head: Deprecated
    icon: exclamation-circle

# Enable dynamic labeling for the changelog section
changelog:
  spot: 1
  sort:
    - 'breaking:grouping1'
    - 'type:grouping1'
  items:
    frame: basic
    show_parts_label: true
    show_tags_label: false
    show_type_label: false
    show_issue_links: true

# Enable dynamic labeling for the release notes section
notes:
  spot: 2
  sort:
    - 'part:grouping1'
  items:
    show_parts_label: true
    show_tags_label: true
    show_type_label: true
    show_lead_label: true
    show_issue_links: true

# Configure the dynamic labels themselves
history:
  labeling:
    singularize_labels: true
    type_label: "Issue Type"
    parts_label: "Components"
    part_label: "Component"
    tags_label: "Labels"
    tag_label: "Label"
    lead_label: "Contributed by"
    join_string: " | "
  items:
    show_issue_links: true

links:
  web:
    href: "https://github.com/DocOps/issuer/issues/{{ tick }}"
    text: "#{{ tick }}"
